#!/usr/bin/env bash
set -euo pipefail

REPO="${YGGTREE_INSTALL_REPO:-logbookfordevs/yggdrasil-worktree}"
VERSION="${YGGTREE_INSTALL_VERSION:-latest}"
ASSET_NAME="${YGGTREE_INSTALL_ASSET:-yggtree-cli.tar.gz}"
INSTALL_ROOT="${YGGTREE_INSTALL_ROOT:-$HOME/.local/share/yggtree}"
BIN_DIR="${YGGTREE_BIN_DIR:-$HOME/.local/bin}"
BIN_PATH="$BIN_DIR/yggtree"
LOCAL_MODE=0
UNLINK_MODE=0

info() {
  printf '\033[1;36m%s\033[0m %s\n' "yggtree" "$1"
}

fail() {
  printf '\033[1;31m%s\033[0m %s\n' "yggtree" "$1" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: install.sh [options]

Install the latest Yggtree CLI release from GitHub, or link this checkout for
local development.

Options:
  --version <tag>         Release tag to install. Defaults to latest.
  --repo <owner/name>     GitHub repository to install from.
  --asset <name>          Release asset name. Defaults to yggtree-cli.tar.gz.
  --install-root <path>   Directory where Yggtree releases are stored.
  --bin-dir <path>        Directory where the yggtree launcher is written.
  --local                 Link the current checkout's bin/yggtree.
  --unlink                Remove the yggtree launcher written by this installer.
  -h, --help              Show this help and exit.

Environment:
  YGGTREE_INSTALL_REPO        Same as --repo.
  YGGTREE_INSTALL_VERSION     Same as --version.
  YGGTREE_INSTALL_ASSET       Same as --asset.
  YGGTREE_INSTALL_ROOT        Same as --install-root.
  YGGTREE_BIN_DIR             Same as --bin-dir.

Examples:
  curl -fsSL https://yggtree.logbookfordevs.com/install.sh | bash
  ./scripts/install.sh --local
  ./scripts/install.sh --unlink
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      [[ -n "${2:-}" ]] || fail "--version requires a value"
      VERSION="$2"
      shift 2
      ;;
    --version=*)
      VERSION="${1#--version=}"
      [[ -n "$VERSION" ]] || fail "--version requires a value"
      shift
      ;;
    --repo)
      [[ -n "${2:-}" ]] || fail "--repo requires a value"
      REPO="$2"
      shift 2
      ;;
    --repo=*)
      REPO="${1#--repo=}"
      [[ -n "$REPO" ]] || fail "--repo requires a value"
      shift
      ;;
    --asset)
      [[ -n "${2:-}" ]] || fail "--asset requires a value"
      ASSET_NAME="$2"
      shift 2
      ;;
    --asset=*)
      ASSET_NAME="${1#--asset=}"
      [[ -n "$ASSET_NAME" ]] || fail "--asset requires a value"
      shift
      ;;
    --install-root)
      [[ -n "${2:-}" ]] || fail "--install-root requires a value"
      INSTALL_ROOT="$2"
      shift 2
      ;;
    --install-root=*)
      INSTALL_ROOT="${1#--install-root=}"
      [[ -n "$INSTALL_ROOT" ]] || fail "--install-root requires a value"
      shift
      ;;
    --bin-dir)
      [[ -n "${2:-}" ]] || fail "--bin-dir requires a value"
      BIN_DIR="$2"
      BIN_PATH="$BIN_DIR/yggtree"
      shift 2
      ;;
    --bin-dir=*)
      BIN_DIR="${1#--bin-dir=}"
      [[ -n "$BIN_DIR" ]] || fail "--bin-dir requires a value"
      BIN_PATH="$BIN_DIR/yggtree"
      shift
      ;;
    --local)
      LOCAL_MODE=1
      shift
      ;;
    --unlink)
      UNLINK_MODE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

find_local_root() {
  if [[ -z "${BASH_SOURCE[0]:-}" || "${BASH_SOURCE[0]}" = "/dev/stdin" || "${BASH_SOURCE[0]}" = "bash" ]]; then
    return 1
  fi

  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  local root_dir
  root_dir="$(cd "$script_dir/.." && pwd)"

  if [[ -f "$root_dir/package.json" && -d "$root_dir/src" && -f "$root_dir/bin/yggtree" ]]; then
    printf '%s' "$root_dir"
    return 0
  fi

  return 1
}

require_node() {
  if ! command -v node >/dev/null 2>&1; then
    fail "node >=20 is required to run Yggtree"
  fi

  local major
  major="$(node -p 'Number(process.versions.node.split(".")[0])' 2>/dev/null || true)"

  if [[ -z "$major" || "$major" -lt 20 ]]; then
    fail "node >=20 is required to run Yggtree; found $(node --version 2>/dev/null || printf 'unknown') at $(command -v node)"
  fi
}

write_launcher() {
  local entry_path="$1"

  if [[ ! -f "$entry_path" ]]; then
    fail "could not find CLI entrypoint at $entry_path"
  fi

  chmod +x "$entry_path"
  mkdir -p "$BIN_DIR"
  local escaped_entry_path
  printf -v escaped_entry_path '%q' "$entry_path"
  cat > "$BIN_PATH" <<LAUNCHER
#!/usr/bin/env bash
set -euo pipefail
# Generated by Yggtree install.sh.
YGGTREE_ENTRYPOINT=$escaped_entry_path

if ! command -v node >/dev/null 2>&1; then
  printf 'yggtree: node >=20 is required to run Yggtree.\n' >&2
  exit 1
fi

YGGTREE_NODE_MAJOR="\$(node -p 'Number(process.versions.node.split(".")[0])' 2>/dev/null || true)"
if [[ -z "\$YGGTREE_NODE_MAJOR" || "\$YGGTREE_NODE_MAJOR" -lt 20 ]]; then
  printf 'yggtree: node >=20 is required to run Yggtree; found %s at %s\n' "\$(node --version 2>/dev/null || printf 'unknown')" "\$(command -v node)" >&2
  exit 1
fi

exec node "\$YGGTREE_ENTRYPOINT" "\$@"
LAUNCHER
  chmod +x "$BIN_PATH"

  info "installed $BIN_PATH"
  info "using node from PATH at runtime"
  info "to remove this Yggtree launcher, run: $0 --unlink"

  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *)
      info "$BIN_DIR is not in PATH for this shell"
      info "add this to your shell config: export PATH=\"$BIN_DIR:\$PATH\""
      ;;
  esac

  case ":$PATH:" in
    *":$BIN_DIR:"*) info "ready: $(command -v yggtree 2>/dev/null || printf '%s' "$BIN_PATH")" ;;
    *) info "ready: $BIN_PATH" ;;
  esac
}

unlink_entrypoint() {
  if [[ ! -e "$BIN_PATH" && ! -L "$BIN_PATH" ]]; then
    info "no Yggtree launcher found at $BIN_PATH"
    return 0
  fi

  local target="script"
  if [[ -L "$BIN_PATH" ]]; then
    target="$(readlink "$BIN_PATH")"
    case "$target" in
      *node_modules/yggtree*)
        fail "$BIN_PATH points to an npm-managed Yggtree install; refusing to remove it"
        ;;
    esac
  elif ! grep -q "Generated by Yggtree install.sh" "$BIN_PATH" 2>/dev/null; then
    fail "$BIN_PATH exists but was not written by this installer; refusing to remove it"
  fi

  rm "$BIN_PATH"
  info "removed $BIN_PATH -> $target"
  info "ready: $(command -v yggtree 2>/dev/null || printf 'yggtree is not on PATH')"
}

if [[ "$UNLINK_MODE" -eq 1 ]]; then
  unlink_entrypoint
  exit 0
fi

if [[ "$LOCAL_MODE" -eq 1 ]]; then
  LOCAL_ROOT="$(find_local_root)" || fail "--local must be run from this repository checkout"
  require_node
  info "using local checkout at $LOCAL_ROOT"
  if ! command -v pnpm >/dev/null 2>&1; then
    fail "pnpm is required for --local installs"
  fi
  info "installing local Yggtree dependencies"
  pnpm --dir "$LOCAL_ROOT" install
  info "building local Yggtree package"
  pnpm --dir "$LOCAL_ROOT" run build
  write_launcher "$LOCAL_ROOT/bin/yggtree"
  exit 0
fi

if ! command -v curl >/dev/null 2>&1; then
  fail "curl is required to install Yggtree"
fi

if ! command -v tar >/dev/null 2>&1; then
  fail "tar is required to install Yggtree"
fi

require_node

if [[ "$VERSION" = "latest" ]]; then
  info "fetching latest release"
  VERSION="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)"
  [[ -n "$VERSION" ]] || fail "could not resolve latest release for $REPO"
fi

case "$VERSION" in
  v*) ;;
  *) VERSION="v$VERSION" ;;
esac

asset_url="https://github.com/$REPO/releases/download/$VERSION/$ASSET_NAME"
checksum_url="$asset_url.sha256"
release_dir="$INSTALL_ROOT/releases/$VERSION"
tmp_dir="$(mktemp -d)"
archive_path="$tmp_dir/$ASSET_NAME"

cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

info "downloading $REPO $VERSION"
curl -fL -o "$archive_path" "$asset_url"

if checksum_text="$(curl -fsSL "$checksum_url" 2>/dev/null)"; then
  expected_checksum="$(printf '%s\n' "$checksum_text" | awk '{print $1}' | head -n 1)"
  if [[ -n "$expected_checksum" ]]; then
    if [[ "$(uname -s)" = "Darwin" ]]; then
      actual_checksum="$(shasum -a 256 "$archive_path" | awk '{print $1}')"
    else
      actual_checksum="$(sha256sum "$archive_path" | awk '{print $1}')"
    fi

    if [[ "$actual_checksum" != "$expected_checksum" ]]; then
      fail "checksum verification failed"
    fi

    info "SHA256 verified"
  fi
else
  info "checksum asset not found; continuing without SHA256 verification"
fi

rm -rf "$release_dir"
mkdir -p "$release_dir"
tar -xzf "$archive_path" -C "$release_dir"

entry_path="$release_dir/bin/yggtree"
if [[ ! -f "$entry_path" ]]; then
  entry_path="$(find "$release_dir" -maxdepth 4 -path '*/bin/yggtree' -type f | head -n 1)"
fi

[[ -n "$entry_path" ]] || fail "release asset did not contain bin/yggtree"

write_launcher "$entry_path"
